spring:
  data:
    mongodb:
      database: jjjl
      host: 124.221.133.243
#      host: 127.0.0.1
      port: 27017
      password: zzy200013
      username: root
      option:
        connect-timeout: 6000
        max-connection-idle-time: 6000
        max-connection-life-time: 6000
        max-wait-time: 6000
        socket-timeout: 0
        server-selection-timeout: 6000

  redis:
    host: 124.221.133.243
#    host: 127.0.0.1
    port: 6379
    password: Xwcdmhsg0
    database: 0
  datasource:
    #连接池配置
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    hikari:
      max-lifetime: 500000
  mvc:
    view:
      prefix: /
      suffix: .jsp


